using UnityEngine;

/// <summary>
/// Which section of the Farm Upgrades menu a track belongs to. Simple, descriptive
/// names (deliberately NOT matching the Helpers/Equipment nav items).
/// </summary>
public enum FarmUpgradeSection
{
    Soil = 0,
    Water = 1,
    Crops = 2,
    Land = 3,
}

/// <summary>
/// Stable effect-key strings. A consumer reads FarmUpgrades.GetBonus(FarmUpgradeKey.X)
/// the same way gameplay reads ResearchManager.GetBonus(StatKey.X). One key per mechanic.
/// </summary>
public static class FarmUpgradeKey
{
    // Soil
    public const string CashYield   = "cash_yield";    // Fertilizer A — +% Cash per harvest
    public const string CoinYield   = "coin_yield";    // Fertilizer B — +% Coins per harvest
    public const string SoilQuality = "soil_quality";  // master multiplier to all crop output
    public const string CompostYield= "compost_yield"; // +% compost from crops/cow
    public const string SoilPrep    = "soil_prep";     // faster baseline tilling

    // Water
    public const string WaterRetention = "water_retention"; // slows dehydration rate
    public const string WaterCapacity  = "water_capacity";  // moisture points above 100
    public const string DryingGrace    = "drying_grace";    // longer grace before dry-out damage
    public const string WateringPower  = "watering_power";  // more moisture per watering action

    // Crops
    public const string GrowthRate       = "growth_rate";       // faster growth
    public const string SlowDecay        = "slow_decay";        // slower dry-out HP decay
    public const string RotResistance    = "rot_resistance";    // slower rot HP decay
    public const string CropHardiness    = "crop_hardiness";    // less threat/weather damage taken
    public const string HeadStart        = "head_start";        // crops start partway into stage 1
    public const string BountifulHarvest = "bountiful_harvest"; // % chance to double a harvest
    public const string SeedRefund       = "seed_refund";       // % chance to refund a seed bag

    // Land (per-zone — see FarmUpgrades.GetZoneBonus / id "zone_level_z{n}")
    public const string ZoneLevel = "zone_level"; // +% to that zone's output
}

/// <summary>
/// ScriptableObject defining one Farm Upgrade track. Levels are stored in UpgradeManager
/// (Coins = permanent, Money = temporary in-run), so this SO carries only definition +
/// cost/effect math. Catalog lives in Resources/FarmUpgrades and is generated by
/// FarmUpgradeCatalogGenerator.
///
/// Lives in IdleFarm.EconomyCore so the EditMode test assembly can exercise the cost/bonus
/// math directly. Assembly-CSharp auto-references EconomyCore, so runtime consumers see it.
/// </summary>
[CreateAssetMenu(fileName = "FarmUpgrade", menuName = "Farm Game/Farm Upgrade", order = 11)]
public class FarmUpgradeData : ScriptableObject
{
    [Header("Identity")]
    [Tooltip("Unique ID, also the UpgradeManager key (e.g. 'growth_rate', 'zone_level_z2').")]
    public string upgradeID = "farm_upgrade_id";
    public string displayName = "Farm Upgrade";
    [TextArea(1, 3)] public string subtext = "What this does";
    [Tooltip("Emoji/icon shown on the card.")]
    public string icon = "🌱";

    [Header("Placement")]
    public FarmUpgradeSection section = FarmUpgradeSection.Soil;
    [Tooltip("Effect key consumers read via FarmUpgrades.GetBonus(...). Use FarmUpgradeKey constants.")]
    public string effectKey = FarmUpgradeKey.GrowthRate;
    [Tooltip("0 = global. 1-4 = this track only affects that zone (Zone Level tracks).")]
    public int zoneTarget = 0;

    [Header("Cap")]
    [Tooltip("Hard cap. 'High-cap' tracks use a large number; capped tracks use ~20-40 (or very low for buffers).")]
    public int maxLevel = 40;
    [Tooltip("Informational: is this one of the long 'high-cap' tracks?")]
    public bool isHighCap = false;

    [Header("Coin cost (permanent, between runs)")]
    public long baseCoinCost = 100;
    [Range(1.0f, 2f)] public float coinGrowthPerLevel = 1.08f;
    [Tooltip("Apply a breakpoint multiplier every N levels (0 = none).")]
    public int coinBreakpointEvery = 25;
    [Range(1f, 5f)] public float coinBreakpointMultiplier = 2.0f;

    [Header("Money cost (temporary, during runs)")]
    public long baseMoneyCost = 5000;
    [Range(1.0f, 3f)] public float moneyGrowthPerLevel = 1.12f;
    public int moneyBreakpointEvery = 25;
    [Range(1f, 5f)] public float moneyBreakpointMultiplier = 2.0f;

    [Header("Effect")]
    [Tooltip("Additive bonus per level. % stats: 0.01 = +1%/level. Buffer stats (capacity): moisture points/level.")]
    public float bonusPerLevel = 0.01f;
    [Tooltip("Display unit, e.g. '%' or 'pts'.")]
    public string bonusUnit = "%";

    // ───────── Cost ─────────

    public long GetCoinCost(int level)
        => FarmUpgradeMath.Cost(baseCoinCost, level, coinGrowthPerLevel, coinBreakpointEvery, coinBreakpointMultiplier);

    public long GetMoneyCost(int level)
        => FarmUpgradeMath.Cost(baseMoneyCost, level, moneyGrowthPerLevel, moneyBreakpointEvery, moneyBreakpointMultiplier);

    public int GetCoinCostInt(int level) => FarmUpgradeMath.ClampToInt(GetCoinCost(level));
    public int GetMoneyCostInt(int level) => FarmUpgradeMath.ClampToInt(GetMoneyCost(level));

    // ───────── Effect ─────────

    public float GetBonus(int level) => FarmUpgradeMath.Bonus(level, bonusPerLevel);

    /// <summary>Human-readable effect text at a level, e.g. "+24%".</summary>
    public string GetBonusText(int level)
    {
        float v = GetBonus(level);
        // Percent-style stats store small per-level fractions; show them as whole percents.
        if (bonusUnit == "%")
            return $"+{Mathf.RoundToInt(v * 100f)}%";
        return $"+{v:0.#} {bonusUnit}";
    }
}
